// Code generated by mockery v1.0.0. DO NOT EDIT.

package yinyoclient

import mock "github.com/stretchr/testify/mock"

// MockEvent is an autogenerated mock type for the Event type
type MockEvent struct {
	mock.Mock
}
