// Code generated by mockery v1.0.0. DO NOT EDIT.

package commands

import event "github.com/openaustralia/yinyo/pkg/event"
import io "io"
import mock "github.com/stretchr/testify/mock"

// MockApp is an autogenerated mock type for the App type
type MockApp struct {
	mock.Mock
}

// CreateEvent provides a mock function with given fields: runName, _a1
func (_m *MockApp) CreateEvent(runName string, _a1 event.Event) error {
	ret := _m.Called(runName, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, event.Event) error); ok {
		r0 = rf(runName, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateRun provides a mock function with given fields: namePrefix
func (_m *MockApp) CreateRun(namePrefix string) (CreateRunResult, error) {
	ret := _m.Called(namePrefix)

	var r0 CreateRunResult
	if rf, ok := ret.Get(0).(func(string) CreateRunResult); ok {
		r0 = rf(namePrefix)
	} else {
		r0 = ret.Get(0).(CreateRunResult)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(namePrefix)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteRun provides a mock function with given fields: runName
func (_m *MockApp) DeleteRun(runName string) error {
	ret := _m.Called(runName)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(runName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetApp provides a mock function with given fields: runName
func (_m *MockApp) GetApp(runName string) (io.Reader, error) {
	ret := _m.Called(runName)

	var r0 io.Reader
	if rf, ok := ret.Get(0).(func(string) io.Reader); ok {
		r0 = rf(runName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(runName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCache provides a mock function with given fields: runName
func (_m *MockApp) GetCache(runName string) (io.Reader, error) {
	ret := _m.Called(runName)

	var r0 io.Reader
	if rf, ok := ret.Get(0).(func(string) io.Reader); ok {
		r0 = rf(runName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(runName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEvents provides a mock function with given fields: runName, lastID
func (_m *MockApp) GetEvents(runName string, lastID string) Events {
	ret := _m.Called(runName, lastID)

	var r0 Events
	if rf, ok := ret.Get(0).(func(string, string) Events); ok {
		r0 = rf(runName, lastID)
	} else {
		r0 = ret.Get(0).(Events)
	}

	return r0
}

// GetExitData provides a mock function with given fields: runName
func (_m *MockApp) GetExitData(runName string) (io.Reader, error) {
	ret := _m.Called(runName)

	var r0 io.Reader
	if rf, ok := ret.Get(0).(func(string) io.Reader); ok {
		r0 = rf(runName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(runName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOutput provides a mock function with given fields: runName
func (_m *MockApp) GetOutput(runName string) (io.Reader, error) {
	ret := _m.Called(runName)

	var r0 io.Reader
	if rf, ok := ret.Get(0).(func(string) io.Reader); ok {
		r0 = rf(runName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(runName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTokenCache provides a mock function with given fields: runName
func (_m *MockApp) GetTokenCache(runName string) (string, error) {
	ret := _m.Called(runName)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(runName)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(runName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutApp provides a mock function with given fields: reader, objectSize, runName
func (_m *MockApp) PutApp(reader io.Reader, objectSize int64, runName string) error {
	ret := _m.Called(reader, objectSize, runName)

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Reader, int64, string) error); ok {
		r0 = rf(reader, objectSize, runName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PutCache provides a mock function with given fields: reader, objectSize, runName
func (_m *MockApp) PutCache(reader io.Reader, objectSize int64, runName string) error {
	ret := _m.Called(reader, objectSize, runName)

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Reader, int64, string) error); ok {
		r0 = rf(reader, objectSize, runName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PutExitData provides a mock function with given fields: reader, objectSize, runName
func (_m *MockApp) PutExitData(reader io.Reader, objectSize int64, runName string) error {
	ret := _m.Called(reader, objectSize, runName)

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Reader, int64, string) error); ok {
		r0 = rf(reader, objectSize, runName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PutOutput provides a mock function with given fields: reader, objectSize, runName
func (_m *MockApp) PutOutput(reader io.Reader, objectSize int64, runName string) error {
	ret := _m.Called(reader, objectSize, runName)

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Reader, int64, string) error); ok {
		r0 = rf(reader, objectSize, runName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StartRun provides a mock function with given fields: runName, output, env, callbackURL
func (_m *MockApp) StartRun(runName string, output string, env map[string]string, callbackURL string) error {
	ret := _m.Called(runName, output, env, callbackURL)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, map[string]string, string) error); ok {
		r0 = rf(runName, output, env, callbackURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
