// Code generated by mockery v1.0.0. DO NOT EDIT.

package cmd

import mock "github.com/stretchr/testify/mock"

// mockClientError is an autogenerated mock type for the clientError type
type mockClientError struct {
	mock.Mock
}

// Error provides a mock function with given fields:
func (_m *mockClientError) Error() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ResponseBody provides a mock function with given fields:
func (_m *mockClientError) ResponseBody() ([]byte, error) {
	ret := _m.Called()

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResponseHeaders provides a mock function with given fields:
func (_m *mockClientError) ResponseHeaders() (int, map[string]string) {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 map[string]string
	if rf, ok := ret.Get(1).(func() map[string]string); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[string]string)
		}
	}

	return r0, r1
}
