// Code generated by mockery v1.0.0. DO NOT EDIT.

package jobdispatcher

import mock "github.com/stretchr/testify/mock"

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

// CreateJobAndToken provides a mock function with given fields: namePrefix, runToken
func (_m *MockClient) CreateJobAndToken(namePrefix string, runToken string) (string, error) {
	ret := _m.Called(namePrefix, runToken)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(namePrefix, runToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(namePrefix, runToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteJobAndToken provides a mock function with given fields: runName
func (_m *MockClient) DeleteJobAndToken(runName string) error {
	ret := _m.Called(runName)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(runName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetToken provides a mock function with given fields: runName
func (_m *MockClient) GetToken(runName string) (string, error) {
	ret := _m.Called(runName)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(runName)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(runName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StartJob provides a mock function with given fields: runName, dockerImage, command, env
func (_m *MockClient) StartJob(runName string, dockerImage string, command []string, env map[string]string) error {
	ret := _m.Called(runName, dockerImage, command, env)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, []string, map[string]string) error); ok {
		r0 = rf(runName, dockerImage, command, env)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
