// Code generated by mockery v1.0.0. DO NOT EDIT.

package event

import mock "github.com/stretchr/testify/mock"

// MockData is an autogenerated mock type for the Data type
type MockData struct {
	mock.Mock
}
