// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// CreateJobAndToken provides a mock function with given fields: namePrefix, runToken
func (_m *Client) CreateJobAndToken(namePrefix string, runToken string) (string, error) {
	ret := _m.Called(namePrefix, runToken)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(namePrefix, runToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(namePrefix, runToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteJobAndToken provides a mock function with given fields: runName
func (_m *Client) DeleteJobAndToken(runName string) error {
	ret := _m.Called(runName)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(runName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetToken provides a mock function with given fields: runName
func (_m *Client) GetToken(runName string) (string, error) {
	ret := _m.Called(runName)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(runName)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(runName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StartJob provides a mock function with given fields: runName, dockerImage, command
func (_m *Client) StartJob(runName string, dockerImage string, command []string) error {
	ret := _m.Called(runName, dockerImage, command)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, []string) error); ok {
		r0 = rf(runName, dockerImage, command)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
