// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Jobs is an autogenerated mock type for the Jobs type
type Jobs struct {
	mock.Mock
}

// Create provides a mock function with given fields: runID, dockerImage, command, maxRunTime, memory
func (_m *Jobs) Create(runID string, dockerImage string, command []string, maxRunTime int64, memory int64) error {
	ret := _m.Called(runID, dockerImage, command, maxRunTime, memory)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, []string, int64, int64) error); ok {
		r0 = rf(runID, dockerImage, command, maxRunTime, memory)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: runID
func (_m *Jobs) Delete(runID string) error {
	ret := _m.Called(runID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(runID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
