// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Jobs is an autogenerated mock type for the Jobs type
type Jobs struct {
	mock.Mock
}

// Create provides a mock function with given fields: runName, dockerImage, command, maxRunTime
func (_m *Jobs) Create(runName string, dockerImage string, command []string, maxRunTime int64) error {
	ret := _m.Called(runName, dockerImage, command, maxRunTime)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, []string, int64) error); ok {
		r0 = rf(runName, dockerImage, command, maxRunTime)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: runName
func (_m *Jobs) Delete(runName string) error {
	ret := _m.Called(runName)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(runName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
