// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import event "github.com/openaustralia/yinyo/pkg/event"
import mock "github.com/stretchr/testify/mock"

// EventIterator is an autogenerated mock type for the EventIterator type
type EventIterator struct {
	mock.Mock
}

// More provides a mock function with given fields:
func (_m *EventIterator) More() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Next provides a mock function with given fields:
func (_m *EventIterator) Next() (event.Event, error) {
	ret := _m.Called()

	var r0 event.Event
	if rf, ok := ret.Get(0).(func() event.Event); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(event.Event)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
